#***************************** Copyright © Jonathon Bell. All rights reserved.
#**
#**
#**  Version : $Header:$
#**
#**
#**  Purpose : Jekyll site configuration file.
#**
#**
#**  See Also: http://pixelcog.com/blog/2013/jekyll-from-scratch-introduction/
#**
#**
#**  Comments: This file uses a tab size of 2 spaces.
#**                                                                     0-0
#**                                                                   (| v |)
#***********************************************************************w*w***

author:           'author'
email:            'jonathon.a.bellgmail.com'
github_username:  'jonathon-bell'
name:             'name'
title:            'title'
description:      'description'
url:              'https://jonathon-bell.github.io/'
theme:            jekyll-theme-minimal
markdown:         'kramdown'
highlighter:      'rouge'
timezone:         'America/Boston'
plugins:          [jekyll-feed, jekyll-paginate]

#*****************************************************************************
