#***************************** Copyright © Jonathon Bell. All rights reserved.
#**
#**
#**  Version : $Header:$
#**
#**
#**  Purpose : Jekyll site configuration file.
#**
#**
#**  Comments: This file uses a tab size of 2 spaces.
#**                                                                     0-0
#**                                                                   (| v |)
#***********************************************************************w*w***

author:           'wol'
email:            'wol@wolery.tech'
github_username:  'wolery'
name:             'name'
title:            'title'
description:      'description'
url:              'https://jonathon-bell.github.io/'
theme:            'minima'
markdown:         'kramdown'
highlighter:      'rouge'
timezone:         'America/Boston'
plugins:          [jekyll-feed, jekyll-paginate]

#*****************************************************************************
